### ISSUE TITLE
남은 기간 수정사항 및 진행방향

### ISSUE THREAD

**Issue by Hong-sk** [Hong-sk/misProject#11]
웹사이트 - %단위와 px단위가 섞여서 난잡하게 보임, %단위로 통합하여 반응형으로 사이트 수정할 것.
게임들 - 게임화면에서 다른 화면으로 이동하는 버튼 x, 구현해서 다른 페이지들 간 이동 원활하게 할 것, 게임들 디자인 조금씩 수정해서 각 게임들의 디자인 조금씩 맞출 것, 추가적인 기능 구현
브랜치 - master 브랜치를 기준으로 다른 브랜치들 merge 후 release 했음. 각 본인 게임들 브랜치 기준으로 pull하고 수정 후에 pull request 보내서 merge 하는 방향으로 진행할 것

개인적으로 있었으면 하는 기능이나 아쉬운 부분이 있으면  댓글 달아주세요.

**Comment by kwj7520** [comment]
초기 화면에서 어딜 클릭해야하는지 알려주는 기능하나면 있으면 좋을거 같아요
