### ISSUE TITLE
숫자야구 완성했어요 확인 부탁드려요

### ISSUE THREAD

**Issue by seungyong2** [Hong-sk/misProject#2]
추가적으로 구현했으면 하는 기능이나 원하는 사항 있으시면 말씀해주세요

**Comment by Hong-sk** [comment]
전에 입력했던 답이 아웃인지, 몇 스트라이크와 몇 볼이 나왔는 지 알 수 있게끔 볼 수 있었으면 좋을 것 같아유

**Comment by hjk950727** [comment]
횟수제한이 있어서 해당 횟수내로 못 맞추면 지는 기능을 구현하면 좋겠습니다.
